fix(container): add no-wrap prop for requirement label
square/maker pull request #114
Opened 2021-08-18 20:21 UTC by ashjtan

## Describe the problem this PR addresses
On website, the `requirement label` was wrapping on overflow. However, it is typically pretty short, so we want it not to wrap, and to have the the `label` accommodate to that size instead.

![image-2021-08-18-13-38-20-317](https://user-images.githubusercontent.com/20190589/129965733-e045befc-1e30-4ee0-8548-759fea52bf90.png)

## Describe the changes in this PR

- Added a `no-wrap` prop that would make the `requirement label` not wrap for its usage in website.
- Added `--space` between the `label` and `requirement-label` so that they are not touching

Before:
<img width="362" alt="Screen Shot 2021-08-18 at 1 08 56 PM" src="https://user-images.githubusercontent.com/20190589/129965942-84a67b0b-8e6c-4235-9a84-98e76223a811.png">

After (with `no-wrap`):
<img width="348" alt="Screen Shot 2021-08-18 at 1 08 20 PM" src="https://user-images.githubusercontent.com/20190589/129965949-429d5168-ee89-4d7d-a42d-c19fbed93f4a.png">

## Other information

2021-08-18 20:31 UTC, landondurnan requested changes
Rather than adding an option prop, I think we can align on making it the default behavior with CSS and avoid adding another option.

2021-08-18 20:51 UTC, mattmewton commented
@landondurnan it was my idea to do the prop since I wasn't sure if we wanted this to be default behavior, but it makes sense to me to be the default

2021-08-18 21:07 UTC, landondurnan commented
I ran the default behavior past design too and they're cool with it.

2021-08-19 19:45 UTC, landondurnan approved these changes

2021-08-19 20:10 UTC, merged