feat(progress-bar): create progress bar component and readme
square/maker pull request #138
Opened 2021-09-22 15:58 UTC by tatems

## Describe the problem this PR addresses
This PR introduces a reusable progress bar component. It has 2 styles (square and rounded/pill), is colour configurable, and 4 different sizes.

## Describe the changes in this PR
The `ProgressBar` component has 4 main inputs:
- `shape`: is either square or rounded/pill (sites that have rounded or pill designs will have the same progress bar shape)
- `color`: controls the color of the inner bar
- `size`: xsmall (4px), small (8px), medium (12px), or large (16px)
- `progress`: a 0-100 number that controls the display of the inner bar

The inner progress bar is a full width bar that uses a transform to match the progress input. It does this instead of a width for performance reasons, as animating width is not nearly as performant.

![Screen Recording 2021-09-22 at 11 52 26 AM](https://user-images.githubusercontent.com/3402466/134378418-1036a277-14c2-4000-b470-e2c84694374c.gif)

2021-09-22 17:57 UTC, landondurnan requested changes
Pretty close, some suggestions for improvements.

2021-09-22 17:57 UTC, landondurnan commented on src/components/ProgressBar/src/ProgressBar.vue
> +				$s[`shape_${shape}`],
The shape class is already on the parent and doesn't need to be set again.

2021-09-22 17:57 UTC, landondurnan commented on src/components/ProgressBar/src/ProgressBar.vue
> +			}"
We should move declarations to the CSS and the calculated values to be computed css properties.

`:style="computedStyles"` then a computed method that returns two properties:
```
{
  '--bar-color': this.color,
  '--fill-percent: MAX_PROGRESS - this.progress
}
```

Then in the styles declare the background property and transform you're doing inline and leverage the inline properties instead.

This is a lot cleaner way of keeping the template tight, the computed parts in JS, and the CSS declarations in styles so everything is where it's expected.

2021-09-22 17:57 UTC, landondurnan commented on src/components/ProgressBar/src/ProgressBar.vue
> +	transition: transform 100ms linear;
I think a similar thing can be done `transition: width ...` and it's less expensive than transforms. See orbit's implementation for ideas: https://github.com/square/orbit/blob/master/src/components/ProgressBar/src/ProgressBar.vue

2021-09-22 17:57 UTC, landondurnan commented on src/components/ProgressBar/src/ProgressBar.vue
> +.ProgressBar.shape_pill {
These shape selectors will get simpler by just leveraging the parent class.

2021-09-22 18:00 UTC, landondurnan requested changes
@tatems One other suggestion. Could you split out the demos, it's a bit intense with the interactions and doesn't add much value. Suggestion: One demo that has the color / progress interaction as you have (but remove all the different sizes). Then have a separate demo for sizes with static props.

2021-09-23 13:20 UTC, tatems commented
@landondurnan Shimaa actually liked the demo as-is, so I think I'll keep it for now.

2021-09-23 16:01 UTC, landondurnan approved these changes

2021-09-23 17:35 UTC, merged