feat!: theming typography
square/maker pull request #215
Opened 2022-01-21 14:49 UTC by pretzelhammer

## Describe the problem this PR addresses

no theming typography

## Describe the changes in this PR

adds theming typography:
- adds themeable `weight` prop on MHeading and MText which allows controlling the font weight
- refactors/fixes the `size` prop on MHeading & MText to go from integer number steps to string named steps (the names came from Design)
- adds `baseSize` and `sizeScale` properties to the theme spec which gives users control over the typographical hierarchy used by the MHeading and MText at a theme-level
- updates the MHeading & MText docs to show off all the new features/refactors

## Other information

2022-01-26 02:26 UTC, landondurnan requested changes
After some initial testing of the impact of changing the base font size, this will have negative consequences and increase the amount of work necessary to rectify a change like this.

I recommend we keep the base size, scale, and steps as they currently are to maintain status quo for our output. Let's revisit the primary issues we're trying to solve with a change like this and determine a safer way to support it given the current state of this code and existing code in consuming apps.

2022-01-26 02:26 UTC, landondurnan commented on src/components/Theme/src/default-theme.js
> +			sizeScale: 1.15,
Changing the base font size and scale is going to have negative consequences on sites that are currently using 16px as the base font size. We should not change these defaults at this time.

2022-01-31 15:42 UTC, pretzelhammer commented
alternative PR: https://github.com/square/maker/pull/216

2022-02-02 17:40 UTC, landondurnan commented
Is this PR still relevant with https://github.com/square/maker/pull/215 open? Are both meant to be reviewed?

2022-02-07 16:02 UTC, pretzelhammer commented
@landondurnan i guess not, i'll close this one

2022-02-07 16:02 UTC, closed without merging